[phases.setup]
nixPkgs = [
    "php83",
    "php83Extensions.gd",
    "php83Extensions.intl",
    "php83Extensions.mbstring",
    "php83Extensions.pdo_mysql",
    "php83Extensions.zip",
    "php83Extensions.bcmath"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --no-scripts",
    "npm ci",
    "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"