services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fuelsops-app

    ports:
      - "8080:80"

    environment:
      APP_NAME: fuelsops
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: fuelsops
      DB_USERNAME: fuelsops
      DB_PASSWORD: fuelsops

    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - ./storage:/var/www/html/storage

    restart: unless-stopped


  mysql:
    image: mysql:8.4

    container_name: fuelsops-mysql

    environment:
      MYSQL_DATABASE: fuelsops
      MYSQL_USER: fuelsops
      MYSQL_PASSWORD: fuelsops
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3307:3306"

    volumes:
      - fuelsops_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

    restart: unless-stopped


volumes:
  fuelsops_mysql_data: